"""Compare stop rules built from cached critic scores (strict label); writes combos.md.

    python3 combos.py

A rule says "stop" (approve) or "revise" for each draft. Cheap checks run first,
and a slower critic's time counts only when the rule actually calls it.
evidence_match passes only at 1; a yes/no draft (0.5) can't be string-checked,
so the gate (rule 4) hands it to llm.
"""

import math
from pathlib import Path

from drafts import load_drafts
from report import load_scores

HERE = Path(__file__).resolve().parent


def run(scores, critic, draft_id):
    """(score or decision, seconds) for one critic on one draft."""
    row = scores[critic][draft_id]
    return (row["score"] if row["score"] is not None else row["decision"] == "approve"), row["seconds"]


# Each rule returns (approved, seconds, called_llm).
def approve_all(s, d):
    return True, 0.0, False


def llm_alone(s, d):
    ok, sec = run(s, "llm", d)
    return ok, sec, True


def evidence_alone(s, d):
    return run(s, "evidence_match", d)[0] == 1, 0.0, False


def gate(s, d):
    if run(s, "evidence_match", d)[0] == 0:
        return False, 0.0, False  # answer not in the evidence: revise, skip llm
    ok, sec = run(s, "llm", d)
    return ok, sec, True


def laya_alone(s, d):
    p, sec = run(s, "laya", d)
    return p >= 0.8, sec, False


def evidence_and_laya(s, d):
    if run(s, "evidence_match", d)[0] != 1:
        return False, 0.0, False
    p, sec = run(s, "laya", d)
    return p >= 0.5, sec, False


def consistency_and_evidence(s, d):
    if run(s, "evidence_match", d)[0] != 1:
        return False, 0.0, False
    c, sec = run(s, "consistency", d)
    return c == 1.0, sec, False


RULES = [
    ("1. approve everything", approve_all, False),
    ("2. llm alone", llm_alone, False),
    ("3. evidence_match alone", evidence_alone, False),
    ("4. gate: evidence_match, then llm", gate, False),
    ("5. laya ≥ 0.8 alone", laya_alone, False),
    ("6. evidence_match = 1 AND laya ≥ 0.5", evidence_and_laya, False),
    ("7. consistency = 1.0 AND evidence_match = 1", consistency_and_evidence, True),  # subset80 only
]


def wilson(k, n, z=1.96):
    """95% Wilson score interval for k successes out of n."""
    if n == 0:
        return None
    p = k / n
    center = (p + z * z / (2 * n)) / (1 + z * z / n)
    half = z * math.sqrt(p * (1 - p) / n + z * z / (4 * n * n)) / (1 + z * z / n)
    return max(0.0, center - half), min(1.0, center + half)


def table(which, scores):
    drafts = load_drafts(which)
    n, n_right = len(drafts), sum(d["correct"] for d in drafts)
    lines = [f"## `{which}`: {n} drafts, {n_right} correct ({n_right / n:.0%})", "",
             "| Rule | Approved | Accuracy when approved (95% CI) | Wrong approvals | Wrongly rejected "
             "| Avg s/draft | llm calls saved vs rule 2 |",
             "|---|---:|---:|---:|---:|---:|---:|"]
    for name, rule, subset80_only in RULES:
        if subset80_only and which != "subset80":
            continue
        results = [(d, *rule(scores, d["draft_id"])) for d in drafts]
        approved = [d for d, ok, _, _ in results if ok]
        right = sum(d["correct"] for d in approved)
        ci = wilson(right, len(approved))
        accuracy = f"{right}/{len(approved)} ({right / len(approved):.0%}, {ci[0]:.0%}–{ci[1]:.0%})" if approved else "—"
        wrong_ok = sum(not d["correct"] for d in approved)
        right_no = n_right - right
        seconds = sum(sec for _, _, sec, _ in results) / n
        saved = 1 - sum(called for *_, called in results) / n
        lines.append(f"| {name} | {len(approved)}/{n} | {accuracy} | {wrong_ok}/{n - n_right} "
                     f"| {right_no}/{n_right} | {seconds:.2f} | {saved:.0%} |")
    return lines


SUMMARY = ("No stop rule is clearly better than approving every draft: every interval for accuracy when approved "
           "overlaps the 51–64% interval for \"approve everything\" on `extra`. "
           "The best trade-off is the gate (rule 4), where the free evidence_match check rejects drafts whose answer is "
           "not in the evidence before calling llm: it is right 66–69% of the time when it stops, against 62–63% for llm alone, "
           "with fewer wrong approvals and 9–12% fewer llm calls. "
           "Laya alone is the most precise on `extra` (69%), but it rejects 70 of 115 right answers and drops to 52% on `subset80`, "
           "so it would mostly just make the loop run more rounds.")


def main():
    scores = load_scores()
    lines = ["# Stop-rule combinations (strict label)", "",
             "Each rule decides, per draft, whether the loop stops (approves) or revises. "
             "Seconds count only the critics the rule actually calls (evidence_match is free). "
             "Generated by `combos.py` from cached scores; no new model calls.", ""]
    for which in ("extra", "subset80"):
        lines += table(which, scores) + [""]
    lines += ["## Summary", "", SUMMARY, "",
              "Notes: \"llm calls saved\" counts calls to the llm critic only; rule 7's time is its 3 extra writer "
              "samples. A yes/no draft (evidence_match = 0.5) is sent to llm by the gate and rejected by rules 3, 6, and 7.", ""]
    text = "\n".join(lines)
    (HERE / "combos.md").write_text(text + "\n", encoding="utf-8")
    print(text)


if __name__ == "__main__":
    main()
